'use client';

import { useEffect, useRef, useState } from 'react';
import { Download, FileSpreadsheet, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { masterDataTabs } from './navigation';
import type { GlobalMasterDataTab } from './global-types';
import type { BulkImportPreview } from './bulk-import-model';

type Item = Record<string, unknown>;
type InputRow = { row: number; values: Item };
type RelatedCatalogs = Partial<Record<GlobalMasterDataTab, Item[]>>;
type PreparedImport = {
  preview: BulkImportPreview;
  rows: InputRow[];
  revision: number;
  fileName: string;
};
type Props = {
  tab: GlobalMasterDataTab;
  items: Item[];
  related?: RelatedCatalogs;
  revision: number;
  disabled: boolean;
  onApply: (items: Item[]) => void;
  announce: (message: string) => void;
};
const pageSize = 50;

/** Download locally generated bytes; no company workbook is sent to an external service. */
function downloadWorkbook(bytes: Uint8Array, name: string): void {
  const url = URL.createObjectURL(
    new Blob([new Uint8Array(bytes).buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    }),
  );
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = name;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 30_000);
}

/** Show editable source values without collapsing deliberate zeroes or boolean false. */
function describeInput(values: Item): string {
  return Object.entries(values)
    .filter(
      ([, value]) => value !== '' && value !== null && value !== undefined,
    )
    .map(
      ([key, value]) =>
        `${key}: ${typeof value === 'string' ? value : JSON.stringify(value)}`,
    )
    .join(' · ');
}

/** Per-tab import stages validated changes in the existing draft; the normal Save/Publish action persists them. */
export function BulkImportControls({
  tab,
  items,
  related,
  revision,
  disabled,
  onApply,
  announce,
}: Props) {
  const label =
    masterDataTabs.find((entry) => entry.value === tab)?.label || tab;
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [prepared, setPrepared] = useState<PreparedImport | null>(null);
  const [page, setPage] = useState(0);
  const fileInput = useRef<HTMLInputElement>(null);
  const operation = useRef(0);
  const inFlight = useRef(false);
  const alive = useRef(true);
  const latest = useRef({ items, related, revision, disabled, onApply });

  // A tab change unmounts this keyed control; late file reads must never apply to another catalog.
  useEffect(() => {
    alive.current = true;
    return () => {
      alive.current = false;
    };
  }, []);
  useEffect(() => {
    latest.current = { items, related, revision, disabled, onApply };
  }, [items, related, revision, disabled, onApply]);

  /** Closing drops only the uncommitted preview and invalidates pending file work. */
  function changeOpen(next: boolean): void {
    operation.current++;
    inFlight.current = false;
    setBusy(false);
    setPrepared(null);
    setError('');
    setPage(0);
    setOpen(next);
  }

  /** Export the exact current-tab format, optionally populated with the current draft for batch updates. */
  async function exportWorkbook(includeCurrent: boolean): Promise<void> {
    if (inFlight.current || (includeCurrent && latest.current.disabled)) return;
    const request = ++operation.current;
    inFlight.current = true;
    setBusy(true);
    setError('');
    try {
      const { createBulkImportWorkbook } =
        await import('./bulk-import-workbook');
      const bytes = await createBulkImportWorkbook(
        tab,
        includeCurrent ? structuredClone(latest.current.items) : undefined,
      );
      if (!alive.current || request !== operation.current) return;
      downloadWorkbook(
        bytes,
        `master-data-${tab}-${includeCurrent ? 'data' : 'template'}.xlsx`,
      );
      announce(
        `${label} Excel ${includeCurrent ? 'data' : 'template'} downloaded.`,
      );
    } catch (cause) {
      if (alive.current && request === operation.current) {
        const message =
          cause instanceof Error ? cause.message : 'Excel download failed.';
        setError(message);
        announce(message);
      }
    } finally {
      if (alive.current && request === operation.current) {
        inFlight.current = false;
        setBusy(false);
      }
    }
  }

  /** Parse and validate against a fresh snapshot, exposing row errors before any draft mutation. */
  async function inspectFile(file: File): Promise<void> {
    if (inFlight.current || latest.current.disabled) return;
    const request = ++operation.current;
    inFlight.current = true;
    setBusy(true);
    setPrepared(null);
    setError('');
    setPage(0);
    try {
      if (!file.name.toLowerCase().endsWith('.xlsx'))
        throw new Error(
          'Choose an .xlsx file created from this tab’s Excel template.',
        );
      if (file.size > 20 * 1024 * 1024)
        throw new Error('Workbook exceeds 20 MB.');
      const [{ readBulkImportWorkbook }, { previewBulkImport }] =
        await Promise.all([
          import('./bulk-import-workbook'),
          import('./bulk-import-model'),
        ]);
      const rows = await readBulkImportWorkbook(
        tab,
        new Uint8Array(await file.arrayBuffer()),
      );
      if (!alive.current || request !== operation.current) return;
      const current = latest.current;
      if (current.disabled)
        throw new Error(
          'This catalog is loading or saving. Wait and select the file again.',
        );
      const preview = previewBulkImport(
        tab,
        rows,
        current.items,
        current.related,
      );
      setPrepared({
        preview,
        rows,
        revision: current.revision,
        fileName: file.name,
      });
    } catch (cause) {
      if (alive.current && request === operation.current)
        setError(
          cause instanceof Error
            ? cause.message
            : 'Unable to read this Excel file.',
        );
    } finally {
      if (alive.current && request === operation.current) {
        inFlight.current = false;
        setBusy(false);
      }
    }
  }

  /** Apply only the reviewed snapshot; changes to this or a referenced catalog require a fresh preview. */
  async function applyPreview(): Promise<void> {
    if (
      !prepared ||
      prepared.preview.issues.length ||
      inFlight.current ||
      latest.current.disabled
    )
      return;
    const request = ++operation.current;
    inFlight.current = true;
    setBusy(true);
    try {
      const { bulkImportContextKey } = await import('./bulk-import-model');
      if (!alive.current || request !== operation.current) return;
      const current = latest.current;
      if (
        current.disabled ||
        current.revision !== prepared.revision ||
        bulkImportContextKey(current.items, current.related) !==
          prepared.preview.contextKey
      )
        throw new Error(
          'The catalog changed after this preview. Select the file again to review the latest changes. / 数据已变化，请重新选择文件预览。',
        );
      current.onApply(structuredClone(prepared.preview.items));
      announce(
        `${label}: ${prepared.preview.added} added, ${prepared.preview.updated} updated in draft. ${tab === 'workflow' ? 'Use Preview & Publish to review project impact.' : 'Use Save this tab to save.'}`,
      );
      changeOpen(false);
    } catch (cause) {
      if (alive.current && request === operation.current)
        setError(
          cause instanceof Error
            ? cause.message
            : 'Import could not be applied.',
        );
    } finally {
      if (alive.current && request === operation.current) {
        inFlight.current = false;
        setBusy(false);
      }
    }
  }

  const preview = prepared?.preview;
  const pages = Math.max(
    1,
    Math.ceil((preview?.changes.length || 0) / pageSize),
  );
  const visibleChanges =
    preview?.changes.slice(page * pageSize, (page + 1) * pageSize) || [];
  return (
    <>
      <Button
        type="button"
        size="sm"
        variant="outline"
        disabled={busy}
        onClick={() => void exportWorkbook(false)}
        aria-label={`Download ${label} Excel template`}
      >
        <Download />{' '}
        <span>
          <span className="hidden sm:inline">Excel </span>Template
        </span>
      </Button>
      <Button
        type="button"
        size="sm"
        variant="outline"
        disabled={disabled || busy}
        onClick={() => changeOpen(true)}
        aria-label={`Bulk import ${label}`}
      >
        <Upload />{' '}
        <span>
          <span className="hidden sm:inline">Bulk </span>Import
        </span>
      </Button>
      {!open && error && (
        <span role="alert" className="basis-full text-xs text-destructive">
          {error}
        </span>
      )}
      <Dialog open={open} onOpenChange={changeOpen}>
        <DialogContent className="sm:max-w-4xl gap-3" aria-busy={busy}>
          <DialogHeader>
            <DialogTitle>Bulk Import · {label}</DialogTitle>
            <DialogDescription>
              Fill the Data sheet in this tab’s Excel template, then review your
              changes. Import updates the draft;{' '}
              {tab === 'workflow'
                ? 'Preview & Publish applies workflow changes.'
                : 'Save this tab saves it.'}
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-wrap items-center gap-2">
            <Button
              type="button"
              size="sm"
              variant="outline"
              disabled={busy}
              onClick={() => void exportWorkbook(false)}
            >
              <Download /> Blank Template
            </Button>
            <Button
              type="button"
              size="sm"
              variant="outline"
              disabled={busy || disabled}
              onClick={() => void exportWorkbook(true)}
            >
              <FileSpreadsheet /> Export Current Data
            </Button>
            <Button
              type="button"
              size="sm"
              disabled={busy || disabled}
              onClick={() => fileInput.current?.click()}
            >
              <Upload /> {busy ? 'Processing…' : 'Choose Excel File'}
            </Button>
            <input
              ref={fileInput}
              type="file"
              accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
              className="sr-only"
              aria-label={`Upload ${label} import workbook`}
              disabled={busy || disabled}
              onChange={(event) => {
                const file = event.target.files?.[0];
                event.target.value = '';
                if (file) void inspectFile(file);
              }}
            />
          </div>
          <p className="text-xs text-muted-foreground">
            Existing records absent from the file stay unchanged. Matching keys
            update records; blank optional cells keep existing values. Export
            current data to retain its IDs.
          </p>
          {error && (
            <p
              role="alert"
              className="text-sm text-destructive whitespace-pre-wrap"
            >
              {error}
            </p>
          )}
          {prepared && preview && (
            <>
              <div
                className="flex flex-wrap items-center gap-x-4 gap-y-1 border-y py-2 text-xs"
                aria-live="polite"
              >
                <strong className="break-all">{prepared.fileName}</strong>
                <span>{preview.added} new</span>
                <span>{preview.updated} updates</span>
                <span>{preview.unchanged} unchanged</span>
                {!!preview.issues.length && (
                  <span className="text-destructive">
                    {preview.issues.length} errors · No changes will be imported
                  </span>
                )}
              </div>
              {!!preview.issues.length && (
                <div
                  role="alert"
                  className="max-h-48 overflow-auto rounded-md border border-destructive/25 p-2 text-xs text-destructive"
                >
                  <ul className="space-y-1">
                    {preview.issues.map((issue, index) => (
                      <li key={index}>
                        Row {issue.row}
                        {issue.column ? ` · ${issue.column}` : ''}:{' '}
                        {issue.message}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              {!!preview.changes.length && (
                <>
                  <div className="min-w-0 rounded-md border">
                    <Table
                      className="text-left text-xs"
                      containerClassName="max-h-[40dvh]"
                      aria-label="Master Data import preview"
                    >
                      <TableHeader className="sticky top-0 bg-muted">
                        <TableRow>
                          <TableHead className="p-2">Action</TableHead>
                          <TableHead className="p-2">Row</TableHead>
                          <TableHead className="p-2">Record</TableHead>
                          <TableHead className="p-2">
                            Values from Excel
                          </TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {visibleChanges.map((change) => (
                          <TableRow
                            key={change.row}
                            className="border-t align-top"
                          >
                            <TableCell className="p-2 capitalize">
                              {change.action}
                            </TableCell>
                            <TableCell className="p-2">{change.row}</TableCell>
                            <TableCell className="p-2 min-w-36">
                              <div className="font-medium">{change.label}</div>
                              <div className="text-muted-foreground [overflow-wrap:anywhere]">
                                {change.key}
                              </div>
                            </TableCell>
                            <TableCell className="p-2 min-w-48 whitespace-pre-wrap [overflow-wrap:anywhere]">
                              {describeInput(
                                prepared.rows.find(
                                  (row) => row.row === change.row,
                                )?.values || {},
                              )}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                  {pages > 1 && (
                    <div className="flex items-center justify-end gap-2 text-xs">
                      <span>
                        Page {page + 1} / {pages}
                      </span>
                      <Button
                        size="sm"
                        variant="outline"
                        disabled={page === 0}
                        onClick={() => setPage((value) => value - 1)}
                      >
                        Previous
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        disabled={page + 1 >= pages}
                        onClick={() => setPage((value) => value + 1)}
                      >
                        Next
                      </Button>
                    </div>
                  )}
                </>
              )}
            </>
          )}
          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => changeOpen(false)}
            >
              Cancel
            </Button>
            <Button
              type="button"
              disabled={
                disabled ||
                busy ||
                !preview ||
                !!preview.issues.length ||
                preview.added + preview.updated === 0
              }
              onClick={() => void applyPreview()}
            >
              Import to Draft
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
