/** Starter project and workflow fixtures used only before SQLite hydration. */

import type { Project, WorkflowStep } from '@/features/projects/types';

export const projects: Project[] = [
  {
    id: 'PRJ-2026-018',
    name: 'Xinglan Retail Cloud Migration & 3-Year Maintenance',
    nameZh: '星澜零售云平台迁移与三年维保',
    client: 'Xinglan Retail',
    clientZh: '星澜零售',
    stage: 'Cost Baseline Approval',
    stageZh: '成本基线确认',
    version: 'V3',
    versionState: 'Draft',
    versionStateZh: '待冻结',
    cost: 'S$ 1,804,000.00',
    delta: '-2.2%',
    nextReview: 'Today · 16:00',
    nextReviewZh: '今天 16:00',
    reviewOwner: 'Manager Chen',
    risk: 'high',
    progress: 60,
    projectStatus: 'cost_review',
    serviceCost: 1324000,
    subcontractCost: 390000,
    totalCost: 1804000,
    totalMandays: 948,
    totalQuote: 2405333.34,
    grossMarginPercent: 25,
  },
  {
    id: 'PRJ-2026-021',
    name: 'Beichen Manufacturing Data Centre Relocation',
    nameZh: '北辰制造数据中心搬迁服务',
    client: 'Beichen Manufacturing',
    clientZh: '北辰制造',
    stage: 'Delivery Review',
    stageZh: '交付评审',
    version: 'V1',
    versionState: 'Draft',
    versionStateZh: '草稿',
    cost: 'S$ 986,400.00',
    delta: '+6.8%',
    nextReview: 'Tomorrow · 11:30',
    nextReviewZh: '明天 11:30',
    reviewOwner: 'Engineer Wang',
    risk: 'medium',
    progress: 42,
    projectStatus: 'delivery_review',
    serviceCost: 702400,
    subcontractCost: 204000,
    totalCost: 986400,
    totalMandays: 486,
    totalQuote: 1315200,
    grossMarginPercent: 25,
  },
  {
    id: 'PRJ-2026-014',
    name: 'Yuanfeng Bank Network Optimisation',
    nameZh: '远峰银行网络优化与驻场支持',
    client: 'Yuanfeng Bank',
    clientZh: '远峰银行',
    stage: 'Quote Review',
    stageZh: '报价评审',
    version: 'V4',
    versionState: 'Confirmed',
    versionStateZh: '已冻结',
    cost: 'S$ 2,460,000.00',
    delta: '+1.4%',
    nextReview: '07 Sep',
    nextReviewZh: '9 月 7 日',
    reviewOwner: 'Director Liu',
    risk: 'low',
    progress: 84,
    projectStatus: 'quote_review',
    serviceCost: 1860000,
    subcontractCost: 420000,
    totalCost: 2460000,
    totalMandays: 1210,
    totalQuote: 3280000,
    grossMarginPercent: 25,
  },
  {
    id: 'PRJ-2026-023',
    name: 'Nanyu Logistics Maintenance Renewal',
    nameZh: '南屿物流设备维保续约',
    client: 'Nanyu Logistics',
    clientZh: '南屿物流',
    stage: 'Input Preparation',
    stageZh: '输入准备',
    version: '—',
    versionState: 'Awaiting import',
    versionStateZh: '待导入',
    cost: 'Pending',
    delta: '—',
    nextReview: '09 Sep',
    nextReviewZh: '9 月 9 日',
    reviewOwner: 'Zhao Min',
    risk: 'medium',
    progress: 24,
    projectStatus: 'input_preparation',
    serviceCost: 0,
    subcontractCost: 0,
    totalCost: 0,
    totalMandays: 0,
    totalQuote: 0,
    grossMarginPercent: 0,
  },
];

export const initialProcessSteps: WorkflowStep[] = [
  {
    code: 'SOLUTION_SCOPE',
    no: '01',
    name: 'Solution Proposal',
    nameZh: '产品方案',
    owner: 'Product Team',
    state: 'completed',
    tone: 'green',
    date: '18 Aug',
    dateZh: '8 月 18 日',
    detail:
      'The solution scope covers cloud migration, disaster recovery, and three years of maintenance.',
    detailZh: '解决方案范围包含云迁移、灾备建设和三年设备维保。',
    input: 'Solution proposal v2.1',
    inputZh: '解决方案说明书 v2.1',
    required: true,
  },
  {
    code: 'TD_EFFORT_REVIEW',
    no: '02',
    name: 'TD Effort Review',
    nameZh: 'TD 人力评估',
    owner: 'Lin / TD',
    state: 'completed',
    tone: 'green',
    date: '21 Aug',
    dateZh: '8 月 21 日',
    detail:
      'Roles, grades, experience requirements, utilisation, and delivery duration have been submitted.',
    detailZh: '已提交角色、级别、经验要求、投入比例及交付周期。',
    input: 'TD_Estimate_0821.xlsx',
    inputZh: 'TD 人力评估文件',
    required: true,
  },
  {
    code: 'DELIVERY_REVIEW',
    no: '03',
    name: 'Delivery & Subcontract Review',
    nameZh: '分包与交付评审',
    owner: 'Wang / PM',
    state: 'completed',
    tone: 'green',
    date: '25 Aug',
    dateZh: '8 月 25 日',
    detail:
      'Delivery was split into two subcontract packages with primary and backup supplier quotes.',
    detailZh: '迁移实施拆为两个分包包件，主供应商和备选供应商均已报价。',
    input: 'Subcontract_Scope_v3.xlsx',
    inputZh: '分包范围与报价 v3',
    required: true,
  },
  {
    code: 'RATE_CONTRACT_IMPORT',
    no: '04',
    name: 'Rate & Contract Import',
    nameZh: '费率与合同导入',
    owner: 'Me',
    state: 'completed',
    tone: 'green',
    date: '27 Aug',
    dateZh: '8 月 27 日',
    detail:
      'The FY26 APAC rate card and supplier framework contract 2026-A17 are linked.',
    detailZh: '采用 FY26 亚太费率卡，并关联主供应商框架合同 2026-A17。',
    input: 'RateCard_FY26 + Contract A17',
    inputZh: '费率卡 FY26 + 合同 A17',
    required: true,
  },
  {
    code: 'COST_BUILD',
    no: '05',
    name: 'Cost Build',
    nameZh: '成本汇总',
    owner: 'Me / Agent',
    state: 'completed',
    tone: 'green',
    date: '29 Aug',
    dateZh: '8 月 29 日',
    detail:
      'Internal labour, subcontract, maintenance, travel, and other costs were consolidated into V1.',
    detailZh: '人力、分包、维保、差旅及其他成本已经汇总为成本 V1。',
    input: 'Cost V1 · S$ 1,720,000.00',
    inputZh: '成本 V1',
    required: true,
  },
  {
    code: 'DIMENSION_CHECK',
    no: '06',
    name: 'Dimension Validation',
    nameZh: '多维校验',
    owner: 'Me / Agent',
    state: 'completed',
    tone: 'green',
    date: '01 Sep',
    dateZh: '9 月 1 日',
    detail:
      'Scope, BU, and grade summaries have been checked against the source lines.',
    detailZh: '已完成 Scope、BU、人员级别三类汇总，分摊比例校验通过。',
    input: '24 / 24 checks passed',
    inputZh: '24 / 24 项校验通过',
    required: true,
  },
  {
    code: 'COST_BASELINE_APPROVAL',
    no: '07',
    name: 'Cost Baseline Approval',
    nameZh: '成本版本确认',
    owner: 'Manager Chen',
    state: 'awaiting_review',
    tone: 'amber',
    date: 'Today · 16:00',
    dateZh: '今天 16:00',
    detail:
      'V3 is S$ 36,000.00 below V2 and awaits approval before becoming the pricing baseline.',
    detailZh: 'V3 较 V2 下降 S$ 36,000.00，等待确认后冻结为报价成本基线。',
    input: 'Cost V3 · Draft',
    inputZh: '成本 V3 · 待冻结',
    required: true,
  },
  {
    code: 'PRICING',
    no: '08',
    name: 'Risk & Pricing',
    nameZh: '利润与定价',
    owner: 'Me',
    state: 'not_started',
    tone: 'gray',
    date: '05 Sep · planned',
    dateZh: '预计 9 月 5 日',
    detail:
      'Set contingency, target margin, discount, and tax after the cost baseline is frozen.',
    detailZh: '需要在成本冻结后设置风险准备金、目标毛利、折扣与税率。',
    input: 'Depends on frozen Cost V3',
    inputZh: '依赖：成本 V3 冻结',
    required: true,
  },
  {
    code: 'QUOTE_PACKAGE',
    no: '09',
    name: 'Quote Package & Assumptions',
    nameZh: '模板与假设',
    owner: 'Me',
    state: 'not_started',
    tone: 'gray',
    date: '08 Sep · planned',
    dateZh: '预计 9 月 8 日',
    detail:
      'Select the client template and save assumptions, exclusions, and client responsibilities.',
    detailZh: '选择客户报价模板，并保存报价假设、排除项和客户责任。',
    input: 'Client template · Not selected',
    inputZh: '客户模板：待选择',
    required: true,
  },
  {
    code: 'COMMERCIAL_ARCHIVE',
    no: '10',
    name: 'History & Maintenance Archive',
    nameZh: '历史与维保归档',
    owner: 'Me / Agent',
    state: 'not_started',
    tone: 'gray',
    date: 'After quote',
    dateZh: '报价后',
    detail:
      'Record the formal quote ID, company-system amount, final differences, and maintenance history.',
    detailZh: '记录正式报价编号、公司平台金额及最终差异，形成历史参考。',
    input: 'Depends on final quote',
    inputZh: '依赖：最终报价输出',
    required: true,
  },
];
